import type { ContractMaster, VehicleLine } from './types';

const v = (
  seq: number,
  brand: string,
  model: string,
  plate: string,
  opts: Partial<VehicleLine> & {
    rentReceivable: number;
    deposit: number;
    serviceReceivable: number;
  },
): VehicleLine => ({
  seq,
  brand,
  model,
  plate,
  selected: opts.selected ?? true,
  locked: opts.locked ?? false,
  rentReceivable: opts.rentReceivable,
  rentActual: opts.rentActual ?? opts.rentReceivable,
  rentRemark: opts.rentRemark ?? '',
  discount: opts.discount ?? 0,
  discountRemark: opts.discountRemark ?? '',
  deposit: opts.deposit,
  serviceReceivable: opts.serviceReceivable,
  serviceActual: opts.serviceActual ?? opts.serviceReceivable,
  serviceItems: opts.serviceItems ?? [
    { name: '基础运维服务', receivable: opts.serviceReceivable * 0.6, actual: (opts.serviceActual ?? opts.serviceReceivable) * 0.6, discount: 0 },
    { name: '平台管理费', receivable: opts.serviceReceivable * 0.4, actual: (opts.serviceActual ?? opts.serviceReceivable) * 0.4, discount: 0 },
  ],
});

export const MOCK_CONTRACTS: ContractMaster[] = [
  {
    id: 'c1',
    contractCode: 'ZL-2026-0888',
    contractType: '正式合同',
    projectName: '嘉兴氢能示范项目',
    customerName: '嘉兴氢途科技',
    payMode: '预付',
    payCycleMonths: 1,
    contractStart: '2026-01-15',
    contractEnd: '2027-01-14',
    businessDept: '业务1部',
    businessPerson: '陈业管',
    allVehiclesReceivableCompleted: false,
    totalReceivable: 256800,
    totalActual: 185900,
    totalDiscount: 1100,
    totalFinanceReceived: 154200,
    children: [
      {
        id: 'r1-1',
        seq: 1,
        auditStatus: '审批通过',
        creator: '张三',
        chargeTime: '2026-07-08 10:00',
        deliveryCount: 2,
        vehicles: [
          v(1, '东风', 'DFH1180', '浙A88888F', { rentReceivable: 18600, deposit: 15000, serviceReceivable: 4800, locked: true }),
          v(2, '福田', 'BJ1180', '浙A66666D', { rentReceivable: 18600, deposit: 15000, serviceReceivable: 4800, locked: true }),
        ],
        receivableTotal: 76800,
        actualTotal: 76300,
        discountTotal: 500,
        financeReceived: 76300,
        arrivalAmount: 76300,
        arrivalTime: '2026-07-09 14:30',
        invoiceMethod: '先开票后付款',
        invoiceStatus: '已开票',
        invoicedAmount: 76300,
        invoiceNote: '租金+服务费，税率13%',
        h2PrepaidReceivable: 20000,
        h2PrepaidActual: 20000,
        before15: true,
        pickupDate: '2026-07-10',
        alignStatus: '已交车',
        specialApproved: false,
      },
      {
        id: 'r1-2',
        seq: 2,
        auditStatus: '审批通过',
        creator: '李四',
        chargeTime: '2026-07-18 09:30',
        deliveryCount: 1,
        vehicles: [
          v(3, '重汽', 'ZZ1187', '浙B12345D', {
            rentReceivable: 32000,
            deposit: 20000,
            serviceReceivable: 12000,
            rentActual: 30000,
            discount: 2000,
            discountRemark: '首月协商',
          }),
        ],
        receivableTotal: 64000,
        actualTotal: 62000,
        discountTotal: 2000,
        financeReceived: 40000,
        arrivalAmount: 40000,
        arrivalTime: '2026-07-19 11:00',
        invoiceMethod: '先付款后开票',
        invoiceStatus: '部分开票',
        invoicedAmount: 0,
        invoiceNote: '待收款齐后开票',
        h2PrepaidReceivable: 0,
        h2PrepaidActual: 0,
        before15: false,
        pickupDate: '2026-07-22',
        alignStatus: '部分收款',
        specialApproved: false,
      },
      {
        id: 'r1-3',
        seq: 3,
        auditStatus: '待审批',
        creator: '王五',
        chargeTime: '2026-07-26 11:00',
        deliveryCount: 1,
        vehicles: [
          v(4, '陕汽', 'SX1313', '浙C66666', { rentReceivable: 8600, deposit: 15000, serviceReceivable: 5000 }),
        ],
        receivableTotal: 28600,
        actualTotal: 28600,
        discountTotal: 0,
        financeReceived: 0,
        arrivalAmount: 0,
        arrivalTime: '-',
        invoiceMethod: '先付款后开票',
        invoiceStatus: '未开票',
        invoicedAmount: 0,
        invoiceNote: '请按合同税率开票',
        h2PrepaidReceivable: 10000,
        h2PrepaidActual: 10000,
        before15: true,
        pickupDate: '2026-07-28',
        alignStatus: '待收款',
        specialApproved: false,
      },
    ],
  },
  {
    id: 'c2',
    contractCode: 'ZL-2026-0901',
    contractType: '正式合同',
    projectName: '杭州城配租赁项目',
    customerName: '杭州博众物流',
    payMode: '预付',
    payCycleMonths: 1,
    contractStart: '2026-03-01',
    contractEnd: '2027-02-28',
    businessDept: '业务2部',
    businessPerson: '王业管',
    allVehiclesReceivableCompleted: false,
    totalReceivable: 132600,
    totalActual: 98000,
    totalDiscount: 0,
    totalFinanceReceived: 65800,
    children: [
      {
        id: 'r2-1',
        seq: 1,
        auditStatus: '审批通过',
        creator: '王业管',
        chargeTime: '2026-06-28 14:00',
        deliveryCount: 2,
        vehicles: [
          v(1, '江淮', '格尔发K5', '浙D88888', { rentReceivable: 16800, deposit: 12000, serviceReceivable: 4200, locked: true }),
          v(2, '解放', 'J6P', '浙D99999', { rentReceivable: 16800, deposit: 12000, serviceReceivable: 4200, locked: true }),
        ],
        receivableTotal: 66200,
        actualTotal: 66200,
        discountTotal: 0,
        financeReceived: 66200,
        arrivalAmount: 66200,
        arrivalTime: '2026-06-29 09:00',
        invoiceMethod: '先开票后付款',
        invoiceStatus: '已开票',
        invoicedAmount: 66200,
        invoiceNote: '租金服务费',
        h2PrepaidReceivable: 0,
        h2PrepaidActual: 0,
        before15: false,
        pickupDate: '2026-06-28',
        alignStatus: '已交车',
        specialApproved: false,
      },
      {
        id: 'r2-2',
        seq: 2,
        auditStatus: '已驳回',
        creator: '王业管',
        chargeTime: '2026-07-15 16:00',
        deliveryCount: 1,
        vehicles: [
          v(3, '福田', '欧曼EST', '浙A77777F', { rentReceivable: 28000, deposit: 15000, serviceReceivable: 10000 }),
        ],
        receivableTotal: 53000,
        actualTotal: 53000,
        discountTotal: 0,
        financeReceived: 30000,
        arrivalAmount: 30000,
        arrivalTime: '2026-07-16 10:00',
        invoiceMethod: '先付款后开票',
        invoiceStatus: '未开票',
        invoicedAmount: 0,
        invoiceNote: '驳回后待重提',
        h2PrepaidReceivable: 0,
        h2PrepaidActual: 0,
        before15: false,
        pickupDate: '2026-07-20',
        alignStatus: '特批放行',
        specialApproved: true,
      },
    ],
  },
  {
    id: 'c3',
    contractCode: 'ZL-2026-0755',
    contractType: '正式合同',
    projectName: '宁波港区短驳',
    customerName: '宁波港运通',
    payMode: '后付',
    payCycleMonths: 1,
    contractStart: '2026-02-10',
    contractEnd: '2027-02-09',
    businessDept: '业务3部',
    businessPerson: '李业管',
    allVehiclesReceivableCompleted: true,
    totalReceivable: 41200,
    totalActual: 41200,
    totalDiscount: 0,
    totalFinanceReceived: 41200,
    children: [
      {
        id: 'r3-1',
        seq: 1,
        auditStatus: '审批通过',
        creator: '李业管',
        chargeTime: '2026-07-05 09:15',
        deliveryCount: 1,
        vehicles: [
          v(1, '东风', 'DFH1180', '浙B55555D', { rentReceivable: 9200, deposit: 18000, serviceReceivable: 4800, locked: true }),
        ],
        receivableTotal: 32000,
        actualTotal: 32000,
        discountTotal: 0,
        financeReceived: 32000,
        arrivalAmount: 32000,
        arrivalTime: '2026-07-06 14:00',
        invoiceMethod: '先开票后付款',
        invoiceStatus: '已开票',
        invoicedAmount: 32000,
        invoiceNote: '标准开票',
        h2PrepaidReceivable: 9200,
        h2PrepaidActual: 9200,
        before15: true,
        pickupDate: '2026-07-08',
        alignStatus: '已付清',
        specialApproved: false,
      },
    ],
  },
];
