import type { ChannelDelivery, HubMessage, MessagePriority } from './types';

function toIso(time: string): string {
  const [date, hm] = time.split(' ');
  return `${date}T${hm}:00+08:00`;
}

function channels(
  createdAt: string,
  opts: { wechatSkipped?: boolean; androidPending?: boolean; harmonyPending?: boolean } = {},
): ChannelDelivery[] {
  const { wechatSkipped = false, androidPending = false, harmonyPending = true } = opts;
  return [
    { client: 'web', status: 'sent', updatedAt: createdAt },
    { client: 'ios', status: 'sent', updatedAt: createdAt },
    {
      client: 'android',
      status: androidPending ? 'pending' : 'sent',
      updatedAt: androidPending ? undefined : createdAt,
    },
    {
      client: 'harmony',
      status: harmonyPending ? 'pending' : 'sent',
      updatedAt: harmonyPending ? undefined : createdAt,
    },
    {
      client: 'wechat_oa',
      status: wechatSkipped ? 'skipped' : 'sent',
      updatedAt: wechatSkipped ? undefined : createdAt,
    },
  ];
}

function fromNotice(
  id: string,
  sourceSystem: HubMessage['sourceSystem'],
  bizType: string,
  bizId: string,
  title: string,
  summary: string,
  detail: string,
  time: string,
  read: boolean,
  audienceRoleIds: string[],
  bizTag: string,
  priority: MessagePriority = 'normal',
  channelOpts?: Parameters<typeof channels>[1],
): HubMessage {
  const createdAt = toIso(time);
  return {
    id,
    sourceSystem,
    bizType,
    bizId,
    title,
    summary,
    detail,
    priority,
    createdAt,
    readAt: read ? createdAt : undefined,
    audienceRoleIds,
    channels: channels(createdAt, channelOpts),
    bizTag,
  };
}

/** 与 workbench SEED_NOTICES 对齐，并补充多系统样例 */
export const SEED_MESSAGES: HubMessage[] = [
  fromNotice(
    'n-release-notes',
    'oneos',
    'system.release',
    'release-v1',
    'v1.2 版本更新',
    '更新后首次进入可查看完整更新日志',
    'OneOS 已发布 V1.2（更新时间：07月16日16:00）。也可从顶栏「版本更新」图标或快速入口随时查阅，并切换查看过往版本。',
    '2026-07-16 16:00',
    false,
    [
      'bizAdmin',
      'bizEnergy',
      'bizSales',
      'ops',
      'procurement',
      'safety',
      'finance',
      'legal',
      'gm',
    ],
    '版本更新',
    'normal',
    { wechatSkipped: true },
  ),
  fromNotice(
    'n-1',
    'oneos',
    'urge.remind',
    't-ops-delivery',
    '沪AD8821',
    '',
    '管理员 张明 对任务「执行交车 · 沪AD8821」发起了催办。请优先处理该待办，完成后状态将同步更新。',
    '2026-07-18 09:12',
    false,
    ['bizAdmin', 'ops', 'gm'],
    '交车任务',
    'high',
  ),
  fromNotice(
    'n-2',
    'oneos',
    'bill.ready',
    't-lease-bill-01',
    '沪东物流 6 月',
    '请于 7 日内完成核对',
    '系统已生成沪东物流 2026 年 6 月租赁账单，应收 ¥186,000。请在 7 天内完成核对并提交财务。',
    '2026-07-14 08:05',
    false,
    ['bizAdmin'],
    '租赁账单',
    'normal',
    { wechatSkipped: true },
  ),
  fromNotice(
    'n-3',
    'oneos',
    'h2.balance',
    't-h2-recharge',
    '嘉定站余额不足预警',
    '当前余额 ¥8,200，低于安全线',
    '嘉定站氢费账户余额已低于安全阈值，建议立即发起预付款充值，避免影响站端加注。',
    '2026-07-18 09:00',
    false,
    ['bizEnergy'],
    '氢费账户',
  ),
  fromNotice(
    'n-4',
    'oneos',
    'approval.arrive',
    't-legal-contract',
    '待审 LC-2026-0888',
    '业务部已提交，请法务审核',
    '新桥冷链租赁合同已到达法务节点，当前已停留超过 24 小时，请尽快审核。',
    '2026-07-16 18:01',
    true,
    ['legal'],
    '租赁合同',
  ),
  fromNotice(
    'n-5',
    'oneos',
    'license.expire',
    't-legal-license',
    '远航能源道路运输证临期',
    '剩余 18 天，请跟进续期',
    '客户「远航能源」道路运输证将于 18 天后到期。业务部需跟进客户续期材料，法务关注风险标签。',
    '2026-07-15 08:10',
    false,
    ['bizSales', 'legal'],
    '证照管理',
  ),
  fromNotice(
    'n-6',
    'oneos',
    'receivable.partial',
    'recv-lhc-202607',
    '绿氢城配',
    '到账金额小于应收',
    '绿氢城配提车应收款已部分到账，差额 ¥12,000，请财务确认并跟进补款。',
    '2026-07-17 16:40',
    false,
    ['finance'],
    '提车应收款',
  ),
  fromNotice(
    'n-7',
    'oneos',
    'system.notice',
    't-safety-accident',
    'AC-2026-041 待复核',
    '司机已上报，请安全部复核',
    '车牌沪BE3310 发生一般事故，材料已上传，请安全部在 SLA 内完成复核。',
    '2026-07-16 12:45',
    false,
    ['safety'],
    '事故复核',
    'normal',
    { wechatSkipped: true },
  ),
  fromNotice(
    'n-8',
    'oneos',
    'overview.risk',
    'weekly-risk-20260718',
    '本周高风险事项汇总',
    '共 11 项跨部门高风险待关注',
    '系统汇总本周各部门高风险预警 11 项，涵盖交车超期、回款超期、加氢未核等，可在经营总览中查看详情。',
    '2026-07-18 07:30',
    false,
    ['gm'],
    '经营总览',
  ),
  fromNotice(
    'n-9',
    'oneos',
    'contract.expire',
    'contract-hc-f1902',
    '到期待还车 · 沪CF1902',
    '合同已到期 6 天',
    '租赁合同已过期，车辆沪CF1902 尚未完成还车流程，请运维跟进。',
    '2026-07-17 08:00',
    true,
    ['ops'],
    '租赁合同',
  ),
  fromNotice(
    'n-10',
    'oneos',
    'payment.unlinked',
    'pay-unlinked-batch',
    '收款入账待关联账单',
    '4 笔收款未关联金额＞0，请业务尽快认领',
    '系统按「到账金额 − 已认领金额」统计，当前有 4 笔收款仍有未关联金额（合计约 ¥5,800）。请业务管理部 / 业务部人员在收款记录中完成账单关联。',
    '2026-07-18 08:20',
    false,
    ['bizAdmin', 'bizSales'],
    '收款记录',
    'normal',
    { wechatSkipped: true },
  ),
  fromNotice(
    'vm-fault-1',
    'vehicle-mid',
    'fault.overdue',
    'VF-20260718-001',
    '故障工单 SLA 超时',
    '沪DK7720 制动系统故障待处理',
    '车辆数据中台检测到故障工单 VF-20260718-001 已超过 SLA 24 小时未闭环，请运维优先处理。',
    '2026-07-18 10:30',
    false,
    ['ops'],
    '故障处理',
    'high',
  ),
  fromNotice(
    'vm-status-1',
    'vehicle-mid',
    'vehicle.status',
    'veh-hc-f1902',
    '车辆状态变更为「停运」',
    '沪CF1902 因合同到期自动停运',
    '车辆数据中台同步：沪CF1902 状态由「在租」变更为「停运」，关联合同 contract-hc-f1902。',
    '2026-07-17 08:05',
    false,
    ['ops', 'bizAdmin'],
    '车辆状态',
  ),
  fromNotice(
    'other-notice-1',
    'other-system',
    'generic.notice',
    'ext-sys-alert-001',
    '第三方能耗平台告警',
    '嘉定站电表读数异常波动',
    '外部能耗监控系统上报嘉定站电表读数异常，请相关同事在 OneOS 内核实后联系第三方平台确认。',
    '2026-07-18 11:00',
    false,
    ['bizEnergy', 'ops'],
    '外部接入',
    'normal',
    { wechatSkipped: true },
  ),
  fromNotice(
    'ext-order-1',
    'external',
    'order.action',
    'O-20260718-009',
    '外部 App A：订单待确认',
    '客户「绿氢城配」新订单待业务确认',
    '外部 App A 推送：订单 O-20260718-009 已创建，请在 App A 内确认交期与价格。',
    '2026-07-18 09:45',
    false,
    ['bizSales'],
    '外部订单',
    'normal',
    { wechatSkipped: true, androidPending: true },
  ),
  fromNotice(
    'ext-settle-1',
    'external',
    'settle.action',
    'S-20260717-003',
    '外部 App B：结算待签章',
    '沪东物流 6 月结算单待财务签章',
    '外部 App B 推送：结算单 S-20260717-003 已生成，请财务在 App B 内完成签章后回传 OneOS。',
    '2026-07-17 14:20',
    false,
    ['finance'],
    '外部结算',
    'normal',
    { wechatSkipped: true, androidPending: true },
  ),
];
