import type { KpiTile, TodoItem, ApprovalCardItem, NoticeItem, ReleaseNote } from './types';

export const MOCK_KPI_TILES: KpiTile[] = [
  {
    id: 'kpi-overdue-bill',
    roleIds: ['bizAdmin', 'finance', 'gm', 'bizSales'],
    module: '租赁合同',
    title: '逾期应收账单积压',
    count: 12,
    unit: '笔',
    level: 'urgent',
    ruleTip: '统计账单到期日已超过 30 天且实收金额 < 应收金额的未结清期款账单',
    details: [
      {
        id: 'd-1',
        title: '杭州城配物流 · 第 3 期租赁账单',
        subTitle: '逾期 14 天 · 待收 ¥45,000.00',
        plate: '浙A88888F',
        customer: '杭州城配物流有限公司',
        amount: 45000,
        href: '/prototypes/lease-contract-management',
      },
      {
        id: 'd-2',
        title: '上海港城配短驳 · 第 2 期租赁账单',
        subTitle: '逾期 22 天 · 待收 ¥68,000.00',
        plate: '沪A12345F',
        customer: '上海港城配短驳服务部',
        amount: 68000,
        href: '/prototypes/lease-contract-management',
      },
    ],
  },
  {
    id: 'kpi-pickup-uncollected',
    roleIds: ['bizAdmin', 'bizSales', 'finance'],
    module: '租赁合同',
    title: '提车应收款待核销',
    count: 5,
    unit: '笔',
    level: 'warning',
    ruleTip: '车辆已交车上线但首期提车保证金/预付款尚未全额到账核销的单据',
    details: [
      {
        id: 'd-3',
        title: '苏州冷链速运 · 提车保证金待核销',
        subTitle: '交车日期: 2026-07-10 · 待核销 ¥30,000.00',
        customer: '苏州冷链速运有限公司',
        amount: 30000,
        href: '/prototypes/lease-contract-management',
      },
    ],
  },
  {
    id: 'kpi-contract-expiring',
    roleIds: ['bizAdmin', 'bizSales', 'legal', 'gm'],
    module: '租赁合同',
    title: '合同 30 天内到期',
    count: 7,
    unit: '份',
    level: 'warning',
    ruleTip: '租期结束日落在未来 30 天内的在租合同',
    details: [
      {
        id: 'd-9',
        title: '宁波港区配送 · 合同将于 08-12 到期',
        subTitle: '剩余 16 天 · 建议启动续租沟通',
        href: '/prototypes/lease-contract-management',
      },
    ],
  },
  {
    id: 'kpi-return-pending',
    roleIds: ['bizAdmin', 'ops', 'finance'],
    module: '租赁合同',
    title: '还车结算待闭环',
    count: 4,
    unit: '单',
    level: 'warning',
    ruleTip: '退租交车已完成但结算单未归档的单据',
    details: [
      {
        id: 'd-10',
        title: '环迪新能源（广州）5 台退租结算',
        subTitle: '待业管/财务会签',
        href: '/prototypes/lease-contract-management',
      },
    ],
  },
  {
    id: 'kpi-unlinked-payments',
    roleIds: ['bizAdmin', 'finance'],
    module: '收款结算',
    title: '银行流水收款未关联',
    count: 4,
    unit: '笔',
    level: 'warning',
    ruleTip: '已入账的对公银行流水尚未与具体合同/账单完成关联打标的款项',
    details: [
      {
        id: 'd-7',
        title: '对公进账 ¥120,000.00 (付款人: 环迪新能源)',
        subTitle: '入账时间: 2026-07-24',
        amount: 120000,
        href: '/prototypes/lease-contract-management',
      },
    ],
  },
  {
    id: 'kpi-billing-draft',
    roleIds: ['bizAdmin', 'finance'],
    module: '收款结算',
    title: '期款账单待出账',
    count: 9,
    unit: '笔',
    level: 'info',
    ruleTip: '本账期应出账但尚未生成的租赁期款账单',
    details: [
      {
        id: 'd-11',
        title: '杭州城配物流 · 08 期账单待生成',
        subTitle: '计划出账日: 2026-08-01',
        href: '/prototypes/lease-contract-management',
      },
    ],
  },
  {
    id: 'kpi-fault-sla-urgent',
    roleIds: ['ops', 'gm'],
    module: '故障处置',
    title: '故障处置 30 天临期/逾期',
    count: 3,
    unit: '起',
    level: 'urgent',
    ruleTip: '距离 30 天闭环截止仅剩 ≤7 天或已逾期的故障事件',
    details: [
      {
        id: 'd-4',
        title: '沪A12345F · 原厂电堆返厂检测',
        subTitle: '已逾期 7 天 · 运维负责人: 刘若楠',
        plate: '沪A12345F',
        href: '/prototypes/vehicle-fault-handling',
      },
      {
        id: 'd-5',
        title: '浙A88888F · 高压绝缘报警',
        subTitle: '距截止仅剩 7 天 · 运维负责人: 王婷婷',
        plate: '浙A88888F',
        href: '/prototypes/vehicle-fault-handling',
      },
    ],
  },
  {
    id: 'kpi-fault-backlog',
    roleIds: ['ops'],
    module: '故障处置',
    title: '待处理故障积压',
    count: 11,
    unit: '起',
    level: 'warning',
    ruleTip: '状态为待派工/排故中且未归档的故障单',
    details: [
      {
        id: 'd-12',
        title: '苏B99888F · 冷却系统异响',
        subTitle: '待派工 · 登记 2 天',
        plate: '苏B99888F',
        href: '/prototypes/vehicle-fault-handling',
      },
    ],
  },
  {
    id: 'kpi-annual-review-due',
    roleIds: ['ops', 'safety'],
    module: '车辆运维',
    title: '本月车辆年审到期',
    count: 8,
    unit: '辆',
    level: 'warning',
    ruleTip: '行驶证/营运证年审截止日落在本月内的在运营车辆',
    details: [
      {
        id: 'd-6',
        title: '京A66666 · 营运证年审',
        subTitle: '截止日: 2026-07-30',
        plate: '京A66666',
        href: '/prototypes/vehicle-management',
      },
    ],
  },
  {
    id: 'kpi-inspection-overdue',
    roleIds: ['ops', 'safety'],
    module: '车辆运维',
    title: '定期巡检逾期未完成',
    count: 6,
    unit: '辆',
    level: 'urgent',
    ruleTip: '计划巡检日已过且未上传巡检结果的车辆',
    details: [
      {
        id: 'd-13',
        title: '浙A88888F · 月度巡检逾期 3 天',
        subTitle: '责任人: 王婷婷',
        plate: '浙A88888F',
        href: '/prototypes/vehicle-management',
      },
    ],
  },
  {
    id: 'kpi-license-abnormal',
    roleIds: ['ops', 'safety', 'bizAdmin'],
    module: '车辆运维',
    title: '证照异常/临期',
    count: 5,
    unit: '辆',
    level: 'warning',
    ruleTip: '行驶证、营运证或保险在 30 天内到期或已异常的车辆',
    details: [
      {
        id: 'd-14',
        title: '沪A12345F · 交强险 15 天后到期',
        subTitle: '请及时续保',
        plate: '沪A12345F',
        href: '/prototypes/vehicle-management',
      },
    ],
  },
  {
    id: 'kpi-energy-arrears',
    roleIds: ['bizEnergy', 'bizAdmin', 'finance'],
    module: '能源加氢',
    title: '氢费账户欠费预警',
    count: 3,
    unit: '户',
    level: 'urgent',
    ruleTip: '能源账户余额不足或已欠费影响加注的客户',
    details: [
      {
        id: 'd-15',
        title: '苏州冷链速运 · 账户余额不足',
        subTitle: '可用余额 ¥800.00',
        href: '/prototypes/lease-contract-management',
      },
    ],
  },
  {
    id: 'kpi-h2-exception',
    roleIds: ['bizEnergy', 'ops'],
    module: '能源加氢',
    title: '加氢异常订单',
    count: 2,
    unit: '笔',
    level: 'info',
    ruleTip: '加注失败、金额异常或待人工复核的加氢订单',
    details: [
      {
        id: 'd-16',
        title: '杭州萧山站 · 加注中断待复核',
        subTitle: '车牌 浙A88888F',
        plate: '浙A88888F',
        href: '/prototypes/lease-contract-management',
      },
    ],
  },
  {
    id: 'kpi-gm-risk-summary',
    roleIds: ['gm'],
    module: '经营风险',
    title: '集团重大履约风险事件',
    count: 2,
    unit: '起',
    level: 'urgent',
    ruleTip: '合同金额超 500 万且逾期超 30 天或涉及诉讼维权的特级风险',
    details: [
      {
        id: 'd-8',
        title: '上海港城配 50 台卡车批量退租纠纷',
        subTitle: '涉案金额 ¥3,400,000.00',
        amount: 3400000,
        href: '/prototypes/lease-contract-management',
      },
    ],
  },
  {
    id: 'kpi-procurement-quote',
    roleIds: ['procurement'],
    module: '采购管理',
    title: '待审定采购报价',
    count: 3,
    unit: '批',
    level: 'warning',
    ruleTip: '已收集报价待部门审定的采购批次',
    details: [
      {
        id: 'd-17',
        title: '2026 Q3 商业险批量采购',
        subTitle: '参评 3 家保险公司',
        href: '/prototypes/vehicle-management',
      },
    ],
  },
  {
    id: 'kpi-legal-litigation',
    roleIds: ['legal', 'gm'],
    module: '法务合规',
    title: '在办诉讼/仲裁',
    count: 2,
    unit: '件',
    level: 'warning',
    ruleTip: '处于诉讼或仲裁程序中的案件',
    details: [
      {
        id: 'd-18',
        title: '港城配退租纠纷仲裁案',
        subTitle: '下一开庭日: 2026-08-18',
        href: '/prototypes/lease-contract-management',
      },
    ],
  },
];

export const MOCK_TODO_ITEMS: TodoItem[] = [
  {
    id: 'todo-1',
    roleIds: ['bizAdmin', 'finance'],
    title: '【提车应收】杭州城配物流 10 台氢能重卡首期款核销',
    bizType: 'pickup-receivable',
    bizTypeLabel: '提车应收',
    urgentLevel: 'overdue',
    slaHoursLeft: -24,
    flowStatus: 'pending',
    managerCanUrge: true,
    received: 20000,
    receivable: 50000,
    createTime: '2026-07-20 10:00',
    href: '/prototypes/lease-contract-management',
    detailSummary: {
      客户名称: '杭州城配物流有限公司',
      车牌批次: '浙A88888F 等 10 辆',
      应收金额: '¥50,000.00',
      已收金额: '¥20,000.00',
      未收差额: '¥30,000.00 (未结清)',
    },
  },
  {
    id: 'todo-2',
    roleIds: ['bizAdmin', 'finance'],
    title: '【租赁账单】上海港城配短驳 2026 年 07 期账单催收',
    bizType: 'lease-bill',
    bizTypeLabel: '租赁账单',
    urgentLevel: 'overdue',
    slaHoursLeft: -72,
    flowStatus: 'pending',
    managerCanUrge: true,
    received: 0,
    receivable: 68000,
    createTime: '2026-07-15 09:30',
    href: '/prototypes/lease-contract-management',
    detailSummary: {
      客户名称: '上海港城配短驳服务部',
      账单期数: '2026年第 07 期',
      应收月租: '¥68,000.00',
      实收月租: '¥0.00',
      逾期天数: '逾期 12 天',
    },
  },
  {
    id: 'todo-3',
    roleIds: ['ops', 'safety'],
    title: '【故障处置】沪A12345F 原厂电堆检测整车厂索赔跟进',
    bizType: 'vehicle-fault',
    bizTypeLabel: '故障处置',
    urgentLevel: 'overdue',
    slaHoursLeft: -168,
    flowStatus: 'processing',
    managerCanUrge: true,
    createTime: '2026-07-10 14:00',
    href: '/prototypes/vehicle-fault-handling',
    detailSummary: {
      故障车牌: '沪A12345F (一汽解放 J6P)',
      故障部位: '燃料电池系统',
      任务状态: '挂起保护中 (整车厂索赔审核)',
      运维负责人: '刘若楠',
    },
  },
  {
    id: 'todo-4',
    roleIds: ['bizAdmin', 'legal'],
    title: '【还车应结】环迪新能源 (广州) 退租车交还结算复核',
    bizType: 'return-settle',
    bizTypeLabel: '还车应结',
    urgentLevel: 'normal',
    slaHoursLeft: 48,
    flowStatus: 'pending',
    managerCanUrge: true,
    submitted: false,
    createTime: '2026-07-25 11:20',
    href: '/prototypes/lease-contract-management',
    detailSummary: {
      退租客户: '环迪新能源（广州）有限公司',
      退租车数: '5 辆 4.5T 氢能轻卡',
      评估车况: '良好无大事故',
      结算状态: '待业管/财务四部门汇总交验',
    },
  },
  {
    id: 'todo-5',
    roleIds: ['procurement'],
    title: '【采购比价】2026 年 Q3 批量车辆商业险采购报价审定',
    bizType: 'insurance-buy',
    bizTypeLabel: '保险采购',
    urgentLevel: 'normal',
    slaHoursLeft: 120,
    flowStatus: 'pending',
    managerCanUrge: false,
    createTime: '2026-07-26 16:00',
    href: '/prototypes/vehicle-management',
    detailSummary: {
      采购批次: '2026年第三季度 50 台重卡商业险',
      参评保险公司: '人保财险 / 平安产险 / 太保财险',
      经办人: '黄倩',
    },
  },
  {
    id: 'todo-6',
    roleIds: ['bizAdmin', 'bizSales'],
    title: '【租赁合同】宁波港区配送续租意向跟进',
    bizType: 'lease-contract',
    bizTypeLabel: '租赁合同',
    urgentLevel: 'normal',
    slaHoursLeft: 96,
    flowStatus: 'pending',
    managerCanUrge: true,
    createTime: '2026-07-27 09:00',
    href: '/prototypes/lease-contract-management',
    detailSummary: {
      客户名称: '宁波港区氢能配送中心',
      到期日: '2026-08-12',
      跟进人: '王磊',
    },
  },
];

export const MOCK_APPROVAL_CARDS: ApprovalCardItem[] = [
  {
    id: 'ap-101',
    type: 'vehicle_procurement',
    typeLabel: '车辆采购',
    title: '东风商用车 20 台 18T 氢能重卡采购合同审批',
    tab: 'todo',
    currentStep: '财务总监审核',
    stayDuration: '1天14小时',
    applyTime: '2026-07-25 10:30',
    applicant: '黄倩 (采购部)',
    isUrgent: true,
    href: '/prototypes/oneos-web-approval',
    flowNodes: [
      { label: '提交采购单', status: 'completed', handler: '黄倩' },
      { label: '采购经理初审', status: 'completed', handler: '赵海峰' },
      { label: '财务总监审核', status: 'current', handler: '陈静' },
      { label: '总经理终审', status: 'pending', handler: '王冕' },
    ],
  },
  {
    id: 'ap-102',
    type: 'lease',
    typeLabel: '租赁合同',
    title: '苏州冷链速运 15 台氢能冷藏车 3 年期租赁合同',
    tab: 'initiated',
    currentStep: '法务合规会签',
    stayDuration: '0天8小时',
    applyTime: '2026-07-26 09:15',
    applicant: '王冕',
    href: '/prototypes/oneos-web-approval',
    initiatorCanUrge: true,
    flowNodes: [
      { label: '提交申请', status: 'completed', handler: '王冕' },
      { label: '业管主管审批', status: 'completed', handler: '王冕' },
      { label: '法务合规会签', status: 'current', handler: '赵律师' },
      { label: '用印归档', status: 'pending', handler: '印章管理员' },
    ],
  },
  {
    id: 'ap-103',
    type: 'transfer',
    typeLabel: '车辆调拨',
    title: '上海金山至杭州萧山 8 台重卡跨省调度审批',
    tab: 'done',
    currentStep: '已审批通过',
    stayDuration: '已闭环',
    applyTime: '2026-07-20 14:00',
    applicant: '刘洋',
    href: '/prototypes/oneos-web-approval',
    flowNodes: [
      { label: '发起调拨', status: 'completed', handler: '刘洋' },
      { label: '运维主管审批', status: 'completed', handler: '刘洋' },
      { label: '调拨出库确认', status: 'completed', handler: '仓库管理员' },
    ],
  },
  {
    id: 'ap-104',
    type: 'return_settlement',
    typeLabel: '还车结算',
    title: '上海港城配短驳 5 台卡车提前退租结算单',
    tab: 'cc',
    currentStep: '总经理最终审批',
    stayDuration: '2天0小时',
    applyTime: '2026-07-24 16:45',
    applicant: '周凯',
    href: '/prototypes/oneos-web-approval',
    ccContent:
      '抄送说明：请业管与财务知悉本单退租结算进度；涉提前退租违约金核算，抄送人无需审批，仅作阅知。',
    flowNodes: [
      { label: '提交结算', status: 'completed', handler: '周凯' },
      { label: '财务核算', status: 'completed', handler: '陈静' },
      { label: '总经理审批', status: 'current', handler: '王冕' },
    ],
  },
];

export const MOCK_NOTICES: NoticeItem[] = [
  {
    id: 'n-1',
    roleIds: ['bizAdmin', 'gm', 'ops'],
    title: '【故障处置催办】F-2026-0701 SLA 仅剩 7 天通知',
    content:
      '单据 F-2026-0701（浙A88888F）距 30 天闭环截止仅剩 7 天，请运维负责人员王婷婷加快索赔材料跟进！',
    sendTime: '2026-07-27 08:30',
    read: false,
    isUrge: true,
    href: '/prototypes/vehicle-fault-handling',
  },
  {
    id: 'n-2',
    roleIds: ['bizAdmin', 'finance'],
    title: '【账单催收督办】上海港城配短驳 07 期账单超期',
    content:
      '上海港城配短驳服务部第 07 期月租账单已超期 12 天，实收 0 元，已抄送财务与业管主管督办。',
    sendTime: '2026-07-26 18:00',
    read: false,
    isUrge: true,
    href: '/prototypes/lease-contract-management',
  },
  {
    id: 'n-3',
    roleIds: [
      'bizAdmin',
      'gm',
      'ops',
      'finance',
      'safety',
      'procurement',
      'legal',
      'bizEnergy',
      'bizSales',
    ],
    title: '【系统发布通知】OneOS V2 全局定版上线通知',
    content:
      'OneOS V2 统一运营管理平台正式发布，支持 Stripe Violet 紫光高规质感、三视图与多角色工作台。',
    sendTime: '2026-07-25 09:00',
    read: true,
    isUrge: false,
    href: '/prototypes/oneos-v2',
  },
];

export const CURRENT_RELEASE_NOTE: ReleaseNote = {
  version: 'V2.1.0',
  date: '2026-07-27',
  title: 'OneOS V2 统一工作台与多角色洞察重磅发布',
  highlights: [
    '快捷入口支持自定义钉选；预警按模块分组高密展示；',
    '运营看板按「角色绑定部门」共用部门模板，多角色 Tab 切换；',
    '待办逾期优先排序；审批支持抄送说明与发起人多通道催办；',
    '通知与版本更新入口落在「原型外壳演示」顶栏。',
  ],
};
