import { LeaseContractRecord } from './types';

export const MOCK_LEASE_CONTRACTS: LeaseContractRecord[] = [
  {
    id: 'lc-001',
    code: 'HT-ZL-2026-001',
    projectName: '嘉兴临港物流燃料电池重卡租赁项目',
    customerName: '杭州嘉氢物流有限公司',
    lesseeCompany: '杭州嘉氢物流有限公司 (B级客户)',
    signingCompany: '羚牛氢能(浙江)供应链管理有限公司',
    contractTemplateCategory: 'formal',
    contractTemplateName: '正式租赁合同模板',
    standardContractName: '2026年标准商用车租赁合同',
    approvalType: 'standard',
    approvalStatus: 'approved',
    contractStatus: 'active',
    currentApprover: '归档完成',
    approvalNodes: [
      { nodeName: '风控合规审核', approver: '李合规', status: 'passed' },
      { nodeName: '法务终审', approver: '王法务', status: 'passed' },
      { nodeName: '总经办审批', approver: '张总经理', status: 'passed' },
    ],
    signingMethod: 'online_esign',
    stampedFiles: ['2026年标准商用车租赁合同_已盖章.pdf'],
    businessDept: '华东业务一部',
    businessOwner: '陈业务',
    creator: '陈业务',
    createdAt: '2026-06-15 10:20',
    updatedAt: '2026-06-18 14:30',
    endDate: '2028-06-14',
    totalVehicles: 6,
    deliveredVehiclesCount: 4,
    returnedVehiclesCount: 1,
    paymentPeriod: '月付',
    h2PaymentMethod: 'prepaid',
    depositAmount: 200000,
    monthlyRentPerVehicle: 12500,
    deliveryRegion: '浙江省·嘉兴市·平湖市',
    deliveryDatePlan: '2026-06-20 至 2026-06-25',
    hasMinimumMileage: true,
    mileagePeriod: 'year',
    mileageTargetKm: 50000,
    delegates: [
      { id: 'del-1', name: '王强', phone: '13812345678', idCard: '330106198801011234' },
      { id: 'del-2', name: '赵刚', phone: '13987654321', idCard: '330106199002025678' },
    ],
    extraFees: [
      { id: 'ef-1', vehiclePlate: '浙AFC891', serviceItem: '车载加氢监测高阶服务', feeAmount: 1200, effectiveDate: '2026-07-01' },
    ],
    tripartiteAgreements: [],
    vehicles: [
      {
        id: 'v-101',
        plateNo: '浙AFC891',
        vin: 'LFN49TH202600101',
        brand: '羚牛氢能',
        model: '49T 氢能重卡 (示范版)',
        vehicleType: '重型半挂牵引车',
        pickupReceivableStatus: 'paid',
        delivered: true,
        deliveredMileage: 1250,
        deliveredBy: '刘运维',
        deliveredAt: '2026-06-20 09:30',
        leaseBillStatus: 'normal',
        returned: false,
        mileageTargetKm: 50000,
        currentMileageKm: 18200,
        remainingMileageKm: 31800,
        mileageProgress: 36,
        mileageForecastStatus: '预计达标',
        deliveryRegion: '嘉兴物流园区',
        plannedDeliveryDate: '2026-06-20',
      },
      {
        id: 'v-102',
        plateNo: '浙AFC892',
        vin: 'LFN49TH202600102',
        brand: '羚牛氢能',
        model: '49T 氢能重卡 (示范版)',
        vehicleType: '重型半挂牵引车',
        pickupReceivableStatus: 'paid',
        delivered: true,
        deliveredMileage: 1100,
        deliveredBy: '刘运维',
        deliveredAt: '2026-06-20 10:15',
        leaseBillStatus: 'normal',
        returned: false,
        mileageTargetKm: 50000,
        currentMileageKm: 19500,
        remainingMileageKm: 30500,
        mileageProgress: 39,
        mileageForecastStatus: '预计达标',
        deliveryRegion: '嘉兴物流园区',
        plannedDeliveryDate: '2026-06-20',
      },
      {
        id: 'v-103',
        plateNo: '浙AFC893',
        vin: 'LFN49TH202600103',
        brand: '羚牛氢能',
        model: '49T 氢能重卡 (标准版)',
        vehicleType: '重型半挂牵引车',
        pickupReceivableStatus: 'paid',
        delivered: true,
        deliveredMileage: 980,
        deliveredBy: '刘运维',
        deliveredAt: '2026-06-21 14:00',
        leaseBillStatus: 'overdue',
        returned: false,
        mileageTargetKm: 45000,
        currentMileageKm: 12400,
        remainingMileageKm: 32600,
        mileageProgress: 28,
        mileageForecastStatus: '预计不足',
        deliveryRegion: '嘉兴物流园区',
        plannedDeliveryDate: '2026-06-21',
      },
      {
        id: 'v-104',
        plateNo: '浙AFC894',
        vin: 'LFN49TH202600104',
        brand: '羚牛氢能',
        model: '49T 氢能重卡 (标准版)',
        vehicleType: '重型半挂牵引车',
        pickupReceivableStatus: 'paid',
        delivered: true,
        deliveredMileage: 1050,
        deliveredBy: '张交付',
        deliveredAt: '2026-06-22 11:20',
        leaseBillStatus: 'normal',
        returned: true,
        returnedAt: '2026-07-15 16:30',
        returnMileage: 46200,
        returnBy: '李还车',
        returnSettlementStatus: 'approving',
        returnApprover: '何斐 (财务经理)',
        mileageTargetKm: 45000,
        currentMileageKm: 46200,
        remainingMileageKm: 0,
        mileageProgress: 100,
        mileageForecastStatus: '已达标',
        deliveryRegion: '嘉兴物流园区',
        plannedDeliveryDate: '2026-06-22',
      },
      {
        id: 'v-105',
        plateNo: '浙AFC895',
        vin: 'LFN49TH202600105',
        brand: '羚牛氢能',
        model: '49T 氢能重卡 (标准版)',
        vehicleType: '重型半挂牵引车',
        pickupReceivableStatus: 'processing',
        delivered: false,
        leaseBillStatus: 'none',
        returned: false,
        mileageTargetKm: 50000,
        deliveryRegion: '嘉兴物流园区',
        plannedDeliveryDate: '2026-07-28',
      },
      {
        id: 'v-106',
        plateNo: '浙AFC896',
        vin: 'LFN49TH202600106',
        brand: '羚牛氢能',
        model: '18T 氢能厢货',
        vehicleType: '中型厢式货车',
        pickupReceivableStatus: 'unpaid',
        delivered: false,
        leaseBillStatus: 'none',
        returned: false,
        mileageTargetKm: 40000,
        deliveryRegion: '嘉兴物流园区',
        plannedDeliveryDate: '2026-08-05',
      },
    ],
    remarks: '首期运力保障重点客户，请优先按日巡检氢堆压力。',
  },
  {
    id: 'lc-002',
    code: 'HT-ZL-2026-002',
    projectName: '宁波港城短驳冷链运输示范项目',
    customerName: '宁波港通冷链物流有限公司',
    lesseeCompany: '宁波港通冷链物流有限公司 (A级客户)',
    signingCompany: '羚牛氢能(浙江)供应链管理有限公司',
    contractTemplateCategory: 'heavy_18t',
    contractTemplateName: '现代18吨正式合同模板',
    standardContractName: '2026年现代18吨氢能厢式货车租赁合同',
    approvalType: 'non_standard',
    approvalStatus: 'approving',
    contractStatus: 'submitted',
    currentApprover: '王法务 (法务终审)',
    approvalNodes: [
      { nodeName: '业务风控初审', approver: '陈业务', status: 'passed' },
      { nodeName: '法务条款特批', approver: '王法务', status: 'pending' },
      { nodeName: '总经理审批', approver: '张总经理', status: 'pending' },
    ],
    signingMethod: 'offline_stamp',
    businessDept: '华东业务二部',
    businessOwner: '林经理',
    creator: '林经理',
    createdAt: '2026-07-10 11:00',
    updatedAt: '2026-07-12 09:15',
    endDate: '2027-07-09',
    totalVehicles: 5,
    deliveredVehiclesCount: 0,
    returnedVehiclesCount: 0,
    paymentPeriod: '季付',
    h2PaymentMethod: 'monthly',
    depositAmount: 100000,
    monthlyRentPerVehicle: 9800,
    deliveryRegion: '浙江省·宁波市·北仑区',
    deliveryDatePlan: '2026-07-25 至 2026-07-30',
    delegates: [
      { id: 'del-3', name: '周明', phone: '13700009999', idCard: '330203198505054321' },
    ],
    extraFees: [],
    tripartiteAgreements: [],
    vehicles: [
      {
        id: 'v-201',
        plateNo: '浙B981H2',
        vin: 'LFN18TH202600201',
        brand: '现代汽车',
        model: '18T 氢燃料电池厢式货车',
        vehicleType: '中型厢式货车',
        pickupReceivableStatus: 'unpaid',
        delivered: false,
        leaseBillStatus: 'normal',
        returned: false,
        deliveryRegion: '宁波梅山港区',
        plannedDeliveryDate: '2026-07-25',
      },
    ],
    remarks: '申请修改特规租金支付逾期违约金比例（由0.05%降至0.03%），走非标审批。',
  },
  {
    id: 'lc-003',
    code: 'HT-ZL-2026-003',
    projectName: '上海青浦城配物流试用测试项目',
    customerName: '上海速捷城配供应链有限公司',
    lesseeCompany: '上海速捷城配供应链有限公司 (B级客户)',
    signingCompany: '上海羚牛氢能科技有限公司',
    contractTemplateCategory: 'trial',
    contractTemplateName: '试用合同模板',
    standardContractName: '2026年商用车试用租赁协议',
    approvalType: 'standard',
    approvalStatus: 'unsubmitted',
    contractStatus: 'draft',
    currentApprover: '未提交',
    signingMethod: 'online_esign',
    businessDept: '沪苏业务部',
    businessOwner: '周专员',
    creator: '周专员',
    createdAt: '2026-07-20 16:45',
    updatedAt: '2026-07-20 16:45',
    endDate: '2026-10-19',
    totalVehicles: 2,
    deliveredVehiclesCount: 0,
    returnedVehiclesCount: 0,
    paymentPeriod: '月付',
    h2PaymentMethod: 'self',
    depositAmount: 30000,
    monthlyRentPerVehicle: 6500,
    deliveryRegion: '上海市·青浦区',
    deliveryDatePlan: '2026-08-01',
    delegates: [],
    extraFees: [],
    tripartiteAgreements: [],
    vehicles: [
      {
        id: 'v-301',
        plateNo: '沪AD001H',
        vin: 'LFN18TH202600301',
        brand: '羚牛氢能',
        model: '18T 氢能厢货',
        vehicleType: '中型厢式货车',
        pickupReceivableStatus: 'unpaid',
        delivered: false,
        leaseBillStatus: 'normal',
        returned: false,
        deliveryRegion: '青浦物流园',
        plannedDeliveryDate: '2026-08-01',
      },
    ],
    remarks: '试用期 3 个月，考核满公里数后可申请转正式租赁合同。',
  },
  {
    id: 'lc-004',
    code: 'HT-ZL-2025-089',
    projectName: '南京江北新区干线物流合作项目',
    customerName: '南京金陵物流集团有限公司',
    lesseeCompany: '南京金陵物流集团有限公司 (A级客户)',
    signingCompany: '羚牛氢能(浙江)供应链管理有限公司',
    contractTemplateCategory: 'formal',
    contractTemplateName: '正式租赁合同模板',
    standardContractName: '2025年标准商用车租赁合同',
    approvalType: 'standard',
    approvalStatus: 'terminated',
    contractStatus: 'terminated',
    currentApprover: '合同到期自然终止',
    signingMethod: 'offline_stamp',
    businessDept: '华东业务一部',
    businessOwner: '陈业务',
    creator: '陈业务',
    createdAt: '2025-06-01 09:00',
    updatedAt: '2026-06-01 18:00',
    endDate: '2026-05-31',
    totalVehicles: 4,
    deliveredVehiclesCount: 4,
    returnedVehiclesCount: 4,
    paymentPeriod: '月付',
    h2PaymentMethod: 'monthly',
    depositAmount: 80000,
    monthlyRentPerVehicle: 11000,
    deliveryRegion: '江苏省·南京市·浦口区',
    deliveryDatePlan: '2025-06-05',
    delegates: [],
    extraFees: [],
    tripartiteAgreements: [],
    vehicles: [],
    remarks: '已全部还车并结算完成，历史档案归档。',
  },
];
