import type { CustomerRisk } from './types';

export const MOCK_CUSTOMERS: CustomerRisk[] = [
  {
    id: 'C-1001',
    name: '杭州博众物流',
    code: 'KH-2026-1001',
    tier: 'LA',
    graceDays: 10,
    region: '华东',
    city: '杭州市',
    creditCode: '91330100MA2XXXXX1A',
    contact: '周经理',
    mobile: '13800001111',
    coopStatus: '已合作',
    legalScore: 18,
    safetyScore: 16,
    financeScore: 14,
    composite: 16,
    redline: false,
    riskLevel: '正常',
    owner: '陈业管',
    bizDept: '业务2部',
    vehicleCount: 28,
    overdueDays: 0,
    contractsInFlight: 3,
    address: '杭州市萧山区某某路88号',
  },
  {
    id: 'C-1002',
    name: '嘉兴氢途科技',
    code: 'KH-2026-1002',
    tier: 'KA',
    graceDays: 15,
    region: '华东',
    city: '嘉兴市',
    creditCode: '91330400MA2XXXXX2B',
    contact: '钱总',
    mobile: '13900002222',
    coopStatus: '已合作',
    legalScore: 20,
    safetyScore: 12,
    financeScore: 8,
    composite: 13,
    redline: false,
    riskLevel: '关注',
    owner: '王业管',
    bizDept: '业务1部',
    vehicleCount: 56,
    overdueDays: 4,
    contractsInFlight: 5,
    address: '嘉兴市南湖区某某大道66号',
  },
  {
    id: 'C-1003',
    name: '温州快达货运',
    code: 'KH-2026-1003',
    tier: 'SMB',
    graceDays: 6,
    region: '华东',
    city: '温州市',
    creditCode: '91330300MA2XXXXX3C',
    contact: '孙老板',
    mobile: '13700003333',
    coopStatus: '已合作',
    legalScore: 6,
    safetyScore: 7,
    financeScore: 5,
    composite: 6,
    redline: true,
    riskLevel: '高风险',
    owner: '李业管',
    bizDept: '业务3部',
    vehicleCount: 4,
    overdueDays: 22,
    contractsInFlight: 1,
    address: '温州市鹿城区某某街12号',
  },
  {
    id: 'C-1004',
    name: '宁波港运通',
    code: 'KH-2026-1004',
    tier: 'LA',
    graceDays: 10,
    region: '华东',
    city: '宁波市',
    creditCode: '91330200MA2XXXXX4D',
    contact: '郑主管',
    mobile: '13600004444',
    coopStatus: '洽谈中',
    legalScore: 15,
    safetyScore: 9,
    financeScore: 11,
    composite: 12,
    redline: false,
    riskLevel: '关注',
    owner: '陈业管',
    bizDept: '业务3部',
    vehicleCount: 14,
    overdueDays: 2,
    contractsInFlight: 2,
    address: '宁波市北仑区港区路1号',
  },
  {
    id: 'C-1005',
    name: '绍兴绿能城配',
    code: 'KH-2026-1005',
    tier: 'SMB',
    graceDays: 6,
    region: '华东',
    city: '绍兴市',
    creditCode: '91330600MA2XXXXX5E',
    contact: '吴女士',
    mobile: '13500005555',
    coopStatus: '已合作',
    legalScore: 17,
    safetyScore: 18,
    financeScore: 16,
    composite: 17,
    redline: false,
    riskLevel: '正常',
    owner: '赵业管',
    bizDept: '业务2部',
    vehicleCount: 7,
    overdueDays: 0,
    contractsInFlight: 1,
    address: '绍兴市越城区某某路5号',
  },
];
