import type { ReturnRow } from './types';

export const MOCK: ReturnRow[] = [
  {
    id: '1',
    docNo: 'RS-202607-0007',
    contractNo: 'ZL-2025-1201',
    projectName: '宁波港区短驳',
    customer: '宁波港运通',
    plate: '浙B12345D',
    brand: '东风',
    model: 'DFH1180',
    bizDept: '业务3部',
    owner: '李业管',
    deliveryTime: '2025-12-01 10:00',
    returnTime: '2026-07-18 16:20',
    returnPerson: '司机王某',
    returnSignDate: '2026-07-18',
    direction: '应收',
    amount: 12800,
    linked: 0,
    status: '客户应付',
    approvalStatus: '审批中',
    hasCarePackage: true,
    hasWearPackage: true,
    hasTirePackage: false,
    safety: {
      status: '已提交',
      submitBy: '安全-赵六',
      fees: [
        { seq: 1, feeItem: '违章罚款代缴', amount: 400, remark: '未处理违章2条', updatedAt: '2026-07-18' },
        { seq: 2, feeItem: '事故客户承担', amount: 1800, remark: '刮擦定损', updatedAt: '2026-07-18' },
      ],
      violations: 2,
      accidents: 1,
    },
    ops: {
      status: '已提交',
      submitBy: '运维-王五',
      fees: [
        { seq: 1, feeItem: '未结算保养费', amount: 1200, remark: '养护保可减免部分', updatedAt: '2026-07-18' },
        { seq: 2, feeItem: '轮胎磨损费', amount: 800, remark: '未购轮胎保', updatedAt: '2026-07-18' },
        { seq: 3, feeItem: '工具损坏丢失费', amount: 300, remark: '', updatedAt: '2026-07-18' },
        { seq: 4, feeItem: '接车服务费', amount: 200, remark: '', updatedAt: '2026-07-18' },
      ],
    },
    biz: {
      status: '已提交',
      submitBy: '业管-张三',
      fees: [
        { seq: 1, feeItem: '尾期租金差额', amount: 2600, remark: '', updatedAt: '2026-07-18' },
        { seq: 2, feeItem: 'ETC通行未结', amount: 800, remark: '设备完好', updatedAt: '2026-07-18' },
        { seq: 3, feeItem: '保养无忧包（养护保）', amount: 1500, remark: '系统按里程自动核算', updatedAt: '系统' },
      ],
    },
    energy: {
      status: '已提交',
      submitBy: '能源-李四',
      fees: [
        { seq: 1, feeItem: '氢量差补缴', amount: 1200, remark: '交还车氢量差', updatedAt: '2026-07-18' },
        { seq: 2, feeItem: '能源费补缴', amount: 0, remark: '', updatedAt: '2026-07-18' },
      ],
    },
  },
  {
    id: '2',
    docNo: 'RS-202607-0009',
    contractNo: 'ZL-2025-0880',
    projectName: '温州短驳',
    customer: '温州快达货运',
    plate: '浙C66666',
    brand: '福田',
    model: '欧曼EST',
    bizDept: '业务3部',
    owner: '赵业管',
    deliveryTime: '2025-10-08 09:00',
    returnTime: '2026-07-20 11:00',
    returnPerson: '司机陈某',
    returnSignDate: '2026-07-20',
    direction: '应退',
    amount: 20000,
    linked: 0,
    status: '应退客户',
    approvalStatus: '审批完成',
    hasCarePackage: false,
    hasWearPackage: false,
    hasTirePackage: false,
    safety: { status: '已提交', submitBy: '安全-赵六', fees: [], violations: 0, accidents: 0 },
    ops: { status: '已提交', submitBy: '运维-王五', fees: [] },
    biz: {
      status: '已提交',
      submitBy: '业管-李三',
      fees: [{ seq: 1, feeItem: '保证金退还', amount: 20000, remark: '无其他扣款', updatedAt: '2026-07-20' }],
    },
    energy: { status: '已提交', submitBy: '能源-李四', fees: [{ seq: 1, feeItem: '能源费退款', amount: 0, remark: '', updatedAt: '2026-07-20' }] },
  },
  {
    id: '3',
    docNo: 'RS-202607-0011',
    contractNo: 'ZL-2025-0666',
    projectName: '嘉兴氢能示范',
    customer: '杭州博众物流',
    plate: '浙A88888F',
    brand: '解放',
    model: 'J6P',
    bizDept: '业务2部',
    owner: '陈业管',
    deliveryTime: '2025-08-01 10:00',
    returnTime: '2026-07-12 15:00',
    returnPerson: '司机周某',
    returnSignDate: '2026-07-12',
    direction: '应收',
    amount: 8600,
    linked: 8600,
    status: '已闭环',
    approvalStatus: '审批完成',
    hasCarePackage: true,
    hasWearPackage: false,
    hasTirePackage: true,
    safety: {
      status: '已提交',
      submitBy: '安全-赵六',
      fees: [{ seq: 1, feeItem: '违章罚款代缴', amount: 200, remark: '', updatedAt: '2026-07-12' }],
      violations: 1,
      accidents: 0,
    },
    ops: {
      status: '已提交',
      submitBy: '运维-王五',
      fees: [
        { seq: 1, feeItem: '清洗费', amount: 150, remark: '', updatedAt: '2026-07-12' },
        { seq: 2, feeItem: '证件丢失费', amount: 0, remark: '', updatedAt: '2026-07-12' },
      ],
    },
    biz: {
      status: '已提交',
      submitBy: '业管-张三',
      fees: [
        { seq: 1, feeItem: '尾期租金差额', amount: 3200, remark: '', updatedAt: '2026-07-12' },
        { seq: 2, feeItem: 'ETC通行未结', amount: 450, remark: '', updatedAt: '2026-07-12' },
      ],
    },
    energy: {
      status: '已提交',
      submitBy: '能源-李四',
      fees: [{ seq: 1, feeItem: '氢量差补缴', amount: 4600, remark: '', updatedAt: '2026-07-12' }],
    },
  },
  {
    id: '4',
    docNo: 'RS-202607-0015',
    contractNo: 'ZL-2025-0999',
    projectName: '杭州城配',
    customer: '嘉兴氢途科技',
    plate: '浙A66666D',
    brand: '陕汽',
    model: '德龙X3000',
    bizDept: '业务1部',
    owner: '王业管',
    deliveryTime: '2025-09-15 09:30',
    returnTime: '2026-07-25 17:00',
    returnPerson: '司机吴某',
    returnSignDate: '2026-07-25',
    direction: '应收',
    amount: 15200,
    linked: 5000,
    status: '结算中',
    approvalStatus: '待审批',
    hasCarePackage: true,
    hasWearPackage: true,
    hasTirePackage: true,
    safety: { status: '待提交', submitBy: '', fees: [], violations: 0, accidents: 0 },
    ops: {
      status: '已提交',
      submitBy: '运维-王五',
      fees: [
        { seq: 1, feeItem: '未结算维修费', amount: 2800, remark: '易损保可减免', updatedAt: '2026-07-25' },
        { seq: 2, feeItem: '广告损坏丢失费', amount: 600, remark: '待拍板价表', updatedAt: '2026-07-25' },
      ],
    },
    biz: {
      status: '待提交',
      submitBy: '',
      fees: [{ seq: 1, feeItem: '尾期租金差额', amount: 4800, remark: '', updatedAt: '—' }],
    },
    energy: {
      status: '已提交',
      submitBy: '能源-李四',
      fees: [{ seq: 1, feeItem: '氢量差补缴', amount: 2100, remark: '', updatedAt: '2026-07-25' }],
    },
  },
];
